"project_id_env": ${{ secrets.CROWDIN_PROJECT_ID }}
"api_token_env": ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true


files: [
  {
    "source": "/src/locales/en.json",
    "translation": "src/locales/%locale%.json",
  }
]