name: Build Insights-WebApp in Shared (Push Tag)

on:
  push:
    tags:
      - '*.*.*-develop'
      - '*.*.*-staging'
      - '*.*.*'

jobs:
  call-workflow:
    uses: weni-ai/actions-workflows/.github/workflows/reusable-workflow.yaml@main
    with:
      image_repository: insights
      dockerfile: "docker/Dockerfile"
      target_repository: weni-ai/kubernetes-manifests-chats
      target_repository_branch: main
      target_application: insights-webapp
      target_patch_file: deployment.json
    secrets: inherit
