name: Run Coverage, Lint Files and Build Project
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
              npm install -g yarn
              yarn install
      - name: Run build translations
        run: yarn translations:build
      - name: Run lint
        run: yarn lint
      - name: Run tests and coverage
        run: yarn test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build application
        run:  yarn build
