name: Run Coverage, Lint Files and Build Project
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Update package list
        run: sudo apt-get update
      
      - name: Install system dependencies for canvas
        run: |
          # Retry logic for package installation
          for i in {1..3}; do
            if sudo apt-get install -y --fix-missing libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++; then
              break
            else
              echo "Attempt $i failed, retrying..."
              sudo apt-get update
              sleep 10
            fi
          done
      
      - name: Install dependencies
        run: |
          npm install
      
      - name: Run lint
        run: npm run lint
      
      - name: Run tests and coverage
        run: npm run test:coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Build application
        run: npm run build
