name: Run Coverage, Lint Files and Build Project
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "CROWDIN_PROJECT_ID=$CROWDIN_PROJECT_ID"
          echo "CROWDIN_API_TOKEN=$CROWDIN_API_TOKEN"
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install system dependencies for canvas
        run: sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
      
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      
      - name: Run lint
        run: yarn lint
      
      - name: Run tests and coverage
        run: yarn test:coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Build application
        run: yarn build
